//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a About me.
        /// </summary>
        public static string aboutMe {
            get {
                return ResourceManager.GetString("aboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hi, I graduated with a First in Electronic and ICT Engineering from the University of Pavia in Italy in 2009 and I got a High School Diploma in Computer Technology in 2006..
        /// </summary>
        public static string aboutMe_Sentence_1 {
            get {
                return ResourceManager.GetString("aboutMe_Sentence_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I have a strong background in Information Technology as I carried out various IT projects during my professional experience..
        /// </summary>
        public static string aboutMe_Sentence_2 {
            get {
                return ResourceManager.GetString("aboutMe_Sentence_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I am a passionate Web Developer (and a continuous learner) with 9 years of professional experience in different European cities..
        /// </summary>
        public static string aboutMe_Sentence_3 {
            get {
                return ResourceManager.GetString("aboutMe_Sentence_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aerospace domain.
        /// </summary>
        public static string aerospaceDomain {
            get {
                return ResourceManager.GetString("aerospaceDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a and certificates.
        /// </summary>
        public static string andCertificates {
            get {
                return ResourceManager.GetString("andCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Banking domain.
        /// </summary>
        public static string bankingDomain {
            get {
                return ResourceManager.GetString("bankingDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Belgium.
        /// </summary>
        public static string Belgium {
            get {
                return ResourceManager.GetString("Belgium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bilingual.
        /// </summary>
        public static string bilingual {
            get {
                return ResourceManager.GetString("bilingual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bologne.
        /// </summary>
        public static string bologna {
            get {
                return ResourceManager.GetString("bologna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Brussels.
        /// </summary>
        public static string Brussels {
            get {
                return ResourceManager.GetString("Brussels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Brussels, Belgium.
        /// </summary>
        public static string brusselsBelgium {
            get {
                return ResourceManager.GetString("brusselsBelgium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a C/C++ Modules and libraries development.
        /// </summary>
        public static string CandCppDllDevelopment {
            get {
                return ResourceManager.GetString("CandCppDllDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I have developed DLLs (C/C++ language) to communicate with external devices through API. I developed two modules (C language) to embed in a Hardware Security Module (HSM) in the domain of cryptography for the brand protection market..
        /// </summary>
        public static string CandCppProjectsDescription1 {
            get {
                return ResourceManager.GetString("CandCppProjectsDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a In the aerospace domain, I developed a tool (C++) to simulate the delays that the different signals can have when received by an array of antennas and their consequences on the Signal-to-noise ratio (S/N)..
        /// </summary>
        public static string CandCppProjectsDescription2 {
            get {
                return ResourceManager.GetString("CandCppProjectsDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A key management tool realized in C++ (Qt framework) for Windows and Linux in the domain of PC security and keys storing..
        /// </summary>
        public static string CandCppProjectsDescription3 {
            get {
                return ResourceManager.GetString("CandCppProjectsDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Certificates.
        /// </summary>
        public static string certificates {
            get {
                return ResourceManager.GetString("certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AngularJs / KnockoutJs + ASP MVC + WCF (insurance domain).
        /// </summary>
        public static string chTitle {
            get {
                return ResourceManager.GetString("chTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contact.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contact me.
        /// </summary>
        public static string contactMe {
            get {
                return ResourceManager.GetString("contactMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CryptoPlayer is a cryptographic calculator. It allows the user to play with the different cryptographic operations. Symmetric and asymmetric cryptography. Hashing functions. RSA key generation. SSL certificate parsing, validation and creation..
        /// </summary>
        public static string cryptoPlayerDescription1 {
            get {
                return ResourceManager.GetString("cryptoPlayerDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The front end  uses AngularJS and Bootstrap, while the backed uses .NET Web API..
        /// </summary>
        public static string cryptoPlayerDescription2 {
            get {
                return ResourceManager.GetString("cryptoPlayerDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cryptographic Calculator.
        /// </summary>
        public static string cryptoPlayerShortTitle {
            get {
                return ResourceManager.GetString("cryptoPlayerShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CryptoPlayer - web application.
        /// </summary>
        public static string cryptoPlayerWebApplication {
            get {
                return ResourceManager.GetString("cryptoPlayerWebApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I developed applications in different domains. Among the others: cryptography, communication with external devices, chip behaviors simulators, printing applications and test oriented applications..
        /// </summary>
        public static string cSharpAppDescription1 {
            get {
                return ResourceManager.GetString("cSharpAppDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a For desktop applications I mainly worked with WPF, MVVM pattern, using DevExpress components..
        /// </summary>
        public static string cSharpAppDescription2 {
            get {
                return ResourceManager.GetString("cSharpAppDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The installer packages for deployment were created through AdvancedInstaller..
        /// </summary>
        public static string cSharpAppDescription3 {
            get {
                return ResourceManager.GetString("cSharpAppDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a C# .Net Applications.
        /// </summary>
        public static string cSharpDotNetApplications {
            get {
                return ResourceManager.GetString("cSharpDotNetApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a C# Fundamentals.
        /// </summary>
        public static string cSharpEgiliaTraining {
            get {
                return ResourceManager.GetString("cSharpEgiliaTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Date of achievement:  28/04/2015.
        /// </summary>
        public static string cSharpExamDate {
            get {
                return ResourceManager.GetString("cSharpExamDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CERTIFICATION EXAMS COMPLETED SUCCESSFULLY.
        /// </summary>
        public static string cSharpExamPassed {
            get {
                return ResourceManager.GetString("cSharpExamPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Programming in C#.
        /// </summary>
        public static string cSharpFoundamentals {
            get {
                return ResourceManager.GetString("cSharpFoundamentals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Specializations in Computer Science..
        /// </summary>
        public static string diplomaDescription {
            get {
                return ResourceManager.GetString("diplomaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Diploma in Information Technology.
        /// </summary>
        public static string diplomaIT {
            get {
                return ResourceManager.GetString("diplomaIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Download as PDF.
        /// </summary>
        public static string downloadAsPDF {
            get {
                return ResourceManager.GetString("downloadAsPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Education.
        /// </summary>
        public static string education {
            get {
                return ResourceManager.GetString("education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Electronic and ICT Engineering.
        /// </summary>
        public static string elctrAndIctEngineeringTitle {
            get {
                return ResourceManager.GetString("elctrAndIctEngineeringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Email Address.
        /// </summary>
        public static string emailAddress {
            get {
                return ResourceManager.GetString("emailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I&apos;ve been working in a multicultural environment where English is the main common language for the last 5 years. During my academic period I took summer courses in English every year in UK, Ireland or Malta..
        /// </summary>
        public static string englishKnowledgeDescription {
            get {
                return ResourceManager.GetString("englishKnowledgeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Experience.
        /// </summary>
        public static string experience {
            get {
                return ResourceManager.GetString("experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fluent.
        /// </summary>
        public static string fluent {
            get {
                return ResourceManager.GetString("fluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a French.
        /// </summary>
        public static string french {
            get {
                return ResourceManager.GetString("french", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I lived in France and Belgium for 6 years. Moreover, having a French speaking wife, I speak French every day..
        /// </summary>
        public static string frenchKnowledgeDescription {
            get {
                return ResourceManager.GetString("frenchKnowledgeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Full Stack Web Developer.
        /// </summary>
        public static string fullStackWebDeveloper {
            get {
                return ResourceManager.GetString("fullStackWebDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FULL STACK WEB DEVELOPER.
        /// </summary>
        public static string fullStackWebDeveloperCapital {
            get {
                return ResourceManager.GetString("fullStackWebDeveloperCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Good.
        /// </summary>
        public static string good {
            get {
                return ResourceManager.GetString("good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AngularJs + Web API.
        /// </summary>
        public static string hTitle {
            get {
                return ResourceManager.GetString("hTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ICT Consultant.
        /// </summary>
        public static string ICTConsultant {
            get {
                return ResourceManager.GetString("ICTConsultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a My team and I developed what we called DeviceTesting application. It allows connecting and communicating with several devices connected to the host pc with the goal to test their functionalities. The list of supported communication protocols is broad as well as the type of devices supported, mainly in the field of smartcatds and microchips..
        /// </summary>
        public static string IronPythonDescription1 {
            get {
                return ResourceManager.GetString("IronPythonDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The application is based on WPF, MVVN pattern, taking advantage of DevExpress components. It embeds IronPython to write the scripting tests. The used .NET logging framework is NLog..
        /// </summary>
        public static string IronPythonDescription2 {
            get {
                return ResourceManager.GetString("IronPythonDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AdvancedInstaller is used for package and deployment..
        /// </summary>
        public static string IronPythonDescription3 {
            get {
                return ResourceManager.GetString("IronPythonDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a IronPython Application for Testing.
        /// </summary>
        public static string ironPythonForTesting {
            get {
                return ResourceManager.GetString("ironPythonForTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ISTQB Certified Software Tester.
        /// </summary>
        public static string ISTQBTesterCertificate {
            get {
                return ResourceManager.GetString("ISTQBTesterCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Italian.
        /// </summary>
        public static string italian {
            get {
                return ResourceManager.GetString("italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Italy.
        /// </summary>
        public static string italy {
            get {
                return ResourceManager.GetString("italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I.T.I.S. A.Volta in Lodi, Italy.
        /// </summary>
        public static string itisVoltaLodi {
            get {
                return ResourceManager.GetString("itisVoltaLodi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a January.
        /// </summary>
        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a English.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Languages.
        /// </summary>
        public static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a languages, trainings.
        /// </summary>
        public static string languagesTtrainings {
            get {
                return ResourceManager.GetString("languagesTtrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a LeclNotes is a teacher eBook. It manages the list of classes, courses, students and votes of a teacher in a school calculating the average votes at different moments of the year. It can be easily extended and customized to be introduced in a school where each teacher has his account..
        /// </summary>
        public static string leclNotesDescription {
            get {
                return ResourceManager.GetString("leclNotesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a LeclNotes Web Application.
        /// </summary>
        public static string leclNotesWebApplication {
            get {
                return ResourceManager.GetString("leclNotesWebApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An error occurred. Please verify that all fields have been correctly filled. &lt;br/&gt;Alternatively, please contact me directly at &lt;a href= \&quot;mailto:mario.fornaroli@yahoo.it\&quot; &gt;mario.fornaroli@yahoo.it&lt;/a&gt;.
        /// </summary>
        public static string mailTxFailure {
            get {
                return ResourceManager.GetString("mailTxFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Message correctly sent, thanks..
        /// </summary>
        public static string mailTxSuccess {
            get {
                return ResourceManager.GetString("mailTxSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a March.
        /// </summary>
        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Master and Bachlor Degree (110/110 cum Laude).
        /// </summary>
        public static string masterAndBachlorDegree {
            get {
                return ResourceManager.GetString("masterAndBachlorDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Master thesis on “Processing of Hyperspectral Remote Sensing data” at University of Extremadura, Spain  (supervisors Prof. P.Gamba from University of Pavia-Italy and Prof. A.Plaza from University of Extremadura-Spain)..
        /// </summary>
        public static string masterThesisDescription {
            get {
                return ResourceManager.GetString("masterThesisDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Message.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modules and Libraries.
        /// </summary>
        public static string modulesAndLibraries {
            get {
                return ResourceManager.GetString("modulesAndLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mother tongue.
        /// </summary>
        public static string motherTongue {
            get {
                return ResourceManager.GetString("motherTongue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a My Expertise.
        /// </summary>
        public static string myExpertise {
            get {
                return ResourceManager.GetString("myExpertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a During my work experience I have developed various web applications, mainly working with the following technologies: Reactjs (both with React only and with Redux+Saga, now moving to React Hooks + Context API), Angular 2+ and AngularJS, plus obviously Jquery-html5-css3-js, (frontend side) and .Net technologies, such as Web API/Asp MVC - Entity Framework, Node.js + Express – Microsoft Sql server and MongoDB (backend side)..
        /// </summary>
        public static string myExpertise_Sentence_1 {
            get {
                return ResourceManager.GetString("myExpertise_Sentence_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a In my first years I also developed Windows applications (mainly C# .Net with WPF), multi-platform applications (C++ Qt framework for Linux), often in the domain of cryptography and security, and I DLLs (C/C++ language) to communicate with external devices through API..
        /// </summary>
        public static string myExpertise_Sentence_2 {
            get {
                return ResourceManager.GetString("myExpertise_Sentence_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I have also developed DLLs (C/C++ language) to communicate with external devices through API. I developed a couple of modules (C language) to embed in a Hardware Security Module in the domain of cryptography for the brand protection market..
        /// </summary>
        public static string myExpertise_Sentence_3 {
            get {
                return ResourceManager.GetString("myExpertise_Sentence_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I enjoy a lot working with Microsoft Visual Studio and Visual Studio Code, depending on the project! They are my favorite IDE. I also developed some project with Qt Creator and Borland/Embarcadero..
        /// </summary>
        public static string myExpertise_Sentence_4 {
            get {
                return ResourceManager.GetString("myExpertise_Sentence_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I am passionate about my job!.
        /// </summary>
        public static string myExpertise_Sentence_5a {
            get {
                return ResourceManager.GetString("myExpertise_Sentence_5a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I constantly train myself, mainly through online courses the evening after the work..
        /// </summary>
        public static string myExpertise_Sentence_5b {
            get {
                return ResourceManager.GetString("myExpertise_Sentence_5b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I have worked also on mobile development projects, targeting Android platform mainly. Coming from a web-developer background it was a natural choice to select multi-platform technology web based as Cordova, with the support of Ionic Framework (using several plugins to reach native functionalities)..
        /// </summary>
        public static string myExpertise_Sentence_Mobile {
            get {
                return ResourceManager.GetString("myExpertise_Sentence_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Online Trainings.
        /// </summary>
        public static string onlineTrainings {
            get {
                return ResourceManager.GetString("onlineTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Other.
        /// </summary>
        public static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SQL development in the context of a data base migration (Banking domain).
        /// </summary>
        public static string otherProjectDescription1 {
            get {
                return ResourceManager.GetString("otherProjectDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Improvements of test environment written in Delphi to comply with Object Oriented Programming (SmartCard domain).
        /// </summary>
        public static string otherProjectDescription2 {
            get {
                return ResourceManager.GetString("otherProjectDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Other minor applications developed with Delphi (SmartCard domain).
        /// </summary>
        public static string otherProjectDescription3 {
            get {
                return ResourceManager.GetString("otherProjectDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a LabVIEW software to monitor and control various external devices using TCP/IP, Serial and USB connections (Aerospace domain).
        /// </summary>
        public static string otherProjectDescription4 {
            get {
                return ResourceManager.GetString("otherProjectDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a At university I developed a couple of projects using Matlab and Assembler MIPS..
        /// </summary>
        public static string otherProjectDescription5 {
            get {
                return ResourceManager.GetString("otherProjectDescription5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Other projects involving technologies not mentioned before are:.
        /// </summary>
        public static string otherProjectSentence {
            get {
                return ResourceManager.GetString("otherProjectSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Other Skills.
        /// </summary>
        public static string otherSkills {
            get {
                return ResourceManager.GetString("otherSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Other technologies.
        /// </summary>
        public static string otherTechnologies {
            get {
                return ResourceManager.GetString("otherTechnologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cordova Android and potentially Ios app - Bookstore domain.
        /// </summary>
        public static string paxMobTitle {
            get {
                return ResourceManager.GetString("paxMobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hi, I&apos;m a software engineer and I love everything related to software development for web and mobile platforms..
        /// </summary>
        public static string pesentingSentence {
            get {
                return ResourceManager.GetString("pesentingSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cordova Android and potentially Ios app - Logistical domain.
        /// </summary>
        public static string porMobTitle {
            get {
                return ResourceManager.GetString("porMobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AngularJs + ASP MVC + Web API - Logistical domain.
        /// </summary>
        public static string porTitle {
            get {
                return ResourceManager.GetString("porTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Present.
        /// </summary>
        public static string present {
            get {
                return ResourceManager.GetString("present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .NET Asp MVC.
        /// </summary>
        public static string projectChDescription1 {
            get {
                return ResourceManager.GetString("projectChDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Front end developed with AngularJs / KnockoutJs + Jquery (plus obviously HTML5-CSS3-JS and other common js libraries).
        /// </summary>
        public static string projectChDescription2 {
            get {
                return ResourceManager.GetString("projectChDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Backend services exposed through WCF.
        /// </summary>
        public static string projectChDescription3 {
            get {
                return ResourceManager.GetString("projectChDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MS SQL Server db with both Entity Framework and ADO .NET (stored procedure and direct sql commands).
        /// </summary>
        public static string projectChDescription4 {
            get {
                return ResourceManager.GetString("projectChDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This web application is an insurance bureau suite of services for the UK market. It involves the following technologies:.
        /// </summary>
        public static string projectChSentence {
            get {
                return ResourceManager.GetString("projectChSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Projects.
        /// </summary>
        public static string projects {
            get {
                return ResourceManager.GetString("projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insurance bureau suite of services.
        /// </summary>
        public static string projectsCh {
            get {
                return ResourceManager.GetString("projectsCh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Online service to automatize documents sending.
        /// </summary>
        public static string projectsH {
            get {
                return ResourceManager.GetString("projectsH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UX professionally designed - Material Design.
        /// </summary>
        public static string projectsHDescription4 {
            get {
                return ResourceManager.GetString("projectsHDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Web application to automatize sending mails and documents through online services.  It involves the following technologies:.
        /// </summary>
        public static string projectsHSentence {
            get {
                return ResourceManager.GetString("projectsHSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bookshop application (Bookstore PAX – Liege, Belgium). It displays different bookshop sections directly linked to bookshop database and websites (best-sellers, events, suggestions, notifications, research book, etc..).
        /// </summary>
        public static string projectsPaxMobSentence {
            get {
                return ResourceManager.GetString("projectsPaxMobSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Web portal to manage a logistic deposit.
        /// </summary>
        public static string projectsPor {
            get {
                return ResourceManager.GetString("projectsPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AngularJs front end  (plus obviously HTML5-CSS3-JS and other common js libraries).
        /// </summary>
        public static string projectsPorDescription1 {
            get {
                return ResourceManager.GetString("projectsPorDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .NET Web API to expose web services.
        /// </summary>
        public static string projectsPorDescription2 {
            get {
                return ResourceManager.GetString("projectsPorDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MS SQL Server db with Entity Framework.
        /// </summary>
        public static string projectsPorDescription3 {
            get {
                return ResourceManager.GetString("projectsPorDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tablet and Smartphone Android app per logistica.
        /// </summary>
        public static string projectsPorMob {
            get {
                return ResourceManager.GetString("projectsPorMob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Online and Offline functioning.
        /// </summary>
        public static string projectsPorMobDescription4 {
            get {
                return ResourceManager.GetString("projectsPorMobDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ionic Material.
        /// </summary>
        public static string projectsPorMobDescription4b {
            get {
                return ResourceManager.GetString("projectsPorMobDescription4b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Various Cordova Plugins (digital signature, camera, file system, white-list, etc...).
        /// </summary>
        public static string projectsPorMobDescription5 {
            get {
                return ResourceManager.GetString("projectsPorMobDescription5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ionic Framework.
        /// </summary>
        public static string projectsPorMobIonicAssetns1 {
            get {
                return ResourceManager.GetString("projectsPorMobIonicAssetns1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Push Notifications.
        /// </summary>
        public static string projectsPorMobNotifications {
            get {
                return ResourceManager.GetString("projectsPorMobNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mobile application to manage products in/out in logistic deposit.  It involves the following technologies:.
        /// </summary>
        public static string projectsPorMobSentence {
            get {
                return ResourceManager.GetString("projectsPorMobSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Web application to manage products in/out in logistic deposit.  It involves the following technologies:.
        /// </summary>
        public static string projectsPorSentence {
            get {
                return ResourceManager.GetString("projectsPorSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Projects with other languages.
        /// </summary>
        public static string projectsWithOtherLanguages {
            get {
                return ResourceManager.GetString("projectsWithOtherLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Python integrated in .Net.
        /// </summary>
        public static string PythonInDotNet {
            get {
                return ResourceManager.GetString("PythonInDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Send.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Software Developer.
        /// </summary>
        public static string softwareDeveloper {
            get {
                return ResourceManager.GetString("softwareDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SOFTWARE DEVELOPER.
        /// </summary>
        public static string softwareDeveloperCapital {
            get {
                return ResourceManager.GetString("softwareDeveloperCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spanish.
        /// </summary>
        public static string spanish {
            get {
                return ResourceManager.GetString("spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I spent 8 months in Spain attending the University of Extremadura participating to the ERASMUS project. DELE (Diploma de Español como Lengua Extranjera) Certificate awarded in 2009..
        /// </summary>
        public static string spanishKnowledgeDescription {
            get {
                return ResourceManager.GetString("spanishKnowledgeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Teacher eBook.
        /// </summary>
        public static string teacherEBook {
            get {
                return ResourceManager.GetString("teacherEBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I&apos;m continuously training myself, mainly through online courses. I do it very often in the evening after the job..
        /// </summary>
        public static string training_online_1 {
            get {
                return ResourceManager.GetString("training_online_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I am a big fun of Microsoft Virtual Academy and I am in the top 100 ranking of my country. That&apos;s where I mainly follow the online courses. Other websites I stay tuned with are Udemy and Coursera..
        /// </summary>
        public static string training_online_2 {
            get {
                return ResourceManager.GetString("training_online_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Trainings and.
        /// </summary>
        public static string trainingsAnd {
            get {
                return ResourceManager.GetString("trainingsAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a University of Pavia, Italy.
        /// </summary>
        public static string universityOfPavia {
            get {
                return ResourceManager.GetString("universityOfPavia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Visit it.
        /// </summary>
        public static string visitIt {
            get {
                return ResourceManager.GetString("visitIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Web developer.
        /// </summary>
        public static string webDeveloper {
            get {
                return ResourceManager.GetString("webDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Windows applications.
        /// </summary>
        public static string WindowsApplications {
            get {
                return ResourceManager.GetString("WindowsApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I’ve worked on a study of feasibility to investigate solutions for building a new ESA (European Space Agency) antennas ground station for future Deep Space missions. In the course of this study I developed two main software..
        /// </summary>
        public static string work_CallistoSpace1 {
            get {
                return ResourceManager.GetString("work_CallistoSpace1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a One to monitor and control various external devices using TCP/IP, Serial and USB connections (LabVIEW)..
        /// </summary>
        public static string work_CallistoSpace2 {
            get {
                return ResourceManager.GetString("work_CallistoSpace2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The second is a simulator (C++) to coordinate the delays in antennas signals reception..
        /// </summary>
        public static string work_CallistoSpace3 {
            get {
                return ResourceManager.GetString("work_CallistoSpace3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Development and implementation of software to manage banking activities. I’ve developed mainly in Cobol and SQL and I’ve provided debugging activities of Java programs..
        /// </summary>
        public static string work_CW1 {
            get {
                return ResourceManager.GetString("work_CW1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I’ve worked on client site (Crediti Agricole bank) as customer support engineer providing solutions for core-banking activities..
        /// </summary>
        public static string work_CW2 {
            get {
                return ResourceManager.GetString("work_CW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I’ve been working as web developer in different projects, mainly in assurance and logistic distribution domain.
        ///I&apos;ve developed web application in form of Single Page Application and we mainly use the following stack: mainly HTML5-CSS-Javascript, AngularJS, Angular 2 and JQuery (client side) and .Net Web API, Asp .NET MVC, Entity Framework and SQL Server (server side)..
        /// </summary>
        public static string work_Euris1 {
            get {
                return ResourceManager.GetString("work_Euris1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The IDE I mainly use are Visual Studio and Visual Studio Code..
        /// </summary>
        public static string work_Euris2 {
            get {
                return ResourceManager.GetString("work_Euris2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I worked as developer in the software tool department. I developed web and desktop applications for internal and external customers, mainly in the domain of cryptography and security..
        /// </summary>
        public static string work_STM1 {
            get {
                return ResourceManager.GetString("work_STM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I mainly developed Windows applications in .Net and Dlls in C/C++. Some other smaller project I realized involved Delphi, and Python languages and Qt framework..
        /// </summary>
        public static string work_STM2 {
            get {
                return ResourceManager.GetString("work_STM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I’ve been working as full-stack developer at the client premises. I’ve been involved in several projects mainly working with the following technologies: FRONTEND: Angular 8 and Reactjs (both with React only and with Redux+Saga, now willing to move to React Hooks + Context API), BACKEND: Node.js (Express and MongoDB)..
        /// </summary>
        public static string work_Sysdata1 {
            get {
                return ResourceManager.GetString("work_Sysdata1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I do daily use (or used in previous projects) various other tool such as automated task-runners, framework to document and test API’s, versioning tool, etc.. I designed and prototyped mobile and web app using Adobe XD..
        /// </summary>
        public static string work_Sysdata2 {
            get {
                return ResourceManager.GetString("work_Sysdata2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Being passionate about web development, I decided to develop web and mobile applications as freelance, when possible :-)..
        /// </summary>
        public static string work_WebFreelance1 {
            get {
                return ResourceManager.GetString("work_WebFreelance1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I mainly work with Asp .NET MVC, Entity Framework and SQL Server (server side), and HTML5-CSS-Javascript, AngularJS and JQuery (client side)..
        /// </summary>
        public static string work_WebFreelance2 {
            get {
                return ResourceManager.GetString("work_WebFreelance2", resourceCulture);
            }
        }
    }
}
